### ISSUE TITLE
The TWS is out of date and must be upgraded.

### ISSUE THREAD

**Issue by Purelightme** [scmhub/ibapi#1]
errors shows below, but i use IB Gateway 10.32, latest version. i am confused this error, could you help me? thanks very much

{"level":"error","reqID":-1,"errCode":503,"errString":"The TWS is out of date and must be upgraded. It does not support market data type requests.","time":"2024-12-05T16:02:24+08:00","message":"<Error>"}

```
client := ibapi.NewEClient(&FWrapper{})
	err := client.Connect("myhost",myport, 5)
	if err != nil {
		return err
	}
	log.Info(context.Background(), "IB connected")

	client.ReqCurrentTime()
	client.ReqMarketDataType(3)
	usdhkd := &ibapi.Contract{
		Symbol:   "USD",
		Currency: "HKD",
		SecType:  "CASH",
		Exchange: "IDEALPRO",
	}
	client.ReqMktData(30, usdhkd, "", false, false, nil)

	<-time.After(time.Second * 600)
	err = client.Disconnect()
	if err != nil {
		return err
	}
	log.Info(context.Background(), "IB disconnected")
	return nil
```

**Comment by pchavanne** [comment]
Hello,
Sorry for the late answer.
Your code is working here with IB Gateway 10.30.
Can you try to get the the latest version of ibapi?
Thank you.
